"""Add order field to projects for manual ordering

Revision ID: 5173f5a2641c
Revises: e202f4bcc67e
Create Date: 2025-08-25 16:08:35.631113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5173f5a2641c'
down_revision = 'e202f4bcc67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
