"""Add linkedin field and increase live_url length

Revision ID: e202f4bcc67e
Revises: 
Create Date: 2025-08-25 15:15:12.918251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e202f4bcc67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.drop_column('linkedin')

    # ### end Alembic commands ###
